README.md, techs/bemjson-to-html.js, test/techs/bemjson-to-html.test.js
=> Renamed `html-from-bemjson` tech

.jshintrc, lib/bundle.js, lib/vow-code.js, techs/bem-xjst.js, techs/bemtree.js, test/.jshintrc, test/techs/bemtree.test.js
=> Added `includeVow` option to `bemtree` tech

techs/bemhtml.js, techs/bemtree.js, test/techs/bemhtml/bemhtml.test.js, test/techs/bemtree.test.js
=> Build mock if there's no base templates

package.json
=> Updated `bem-xjst` to `1.0.0`

README.md, techs/bem-xjst.js, techs/bemhtml.js
=> Got rid of `xjst` suffix

.travis.yml, package.json, test/techs/bemhtml/bemhtml--browser.test.js, test/techs/bemhtml/bemhtml--node.test.js, test/techs/bemhtml/bemhtml--ym.test.js, test/techs/bemhtml/bemhtml.test.js, test/techs/bemjson-to-html.test.js, test/techs/bemtree.test.js
=> Issue 62 Move to mock-enb

package.json
=> Update vow to 0.4.10 and bem-xjst to 1.0.3

techs/bem-xjst.js, techs/bemhtml.js, techs/bemjson-to-html.js, techs/bemtree.js
Resolved #67 
@blond @sipayRT @tavriaforever 
=> #67 Actualize jsdoc

techs/bemhtml.js, techs/bemjson-to-html.js, techs/bemtree.js
=> #74 Fix requirements paths inside jsdoc examples

package.json, techs/bem-xjst.js, test/techs/bemhtml/bemhtml.test.js, test/techs/bemtree.test.js
=> Throw error if there is no base templates

techs/bem-xjst.js
Resolved #78 
@blond @tadatuta 
=> Support BEMContext from exports

package.json
=> Update bem-xjst to 1.2.1

lib/bundle.js, package.json, test/techs/bemhtml/bemhtml--browser.test.js, test/techs/bemhtml/bemhtml--node.test.js, test/techs/bemhtml/bemhtml--ym.test.js
=> Inline CommonJS requires

techs/bem-xjst.js, techs/bemhtml.js, techs/bemtree.js, test/techs/bemhtml/bemhtml.test.js
=> Prepared techs for inheritance

techs/bem-xjst.js, test/techs/bemhtml/bemhtml.test.js, test/techs/bemtree.test.js
=> Not translate files with `.js` extension

techs/bem-xjst.js, techs/bemhtml.js
=> Removed `cache` option

CHANGELOG.md
=> Added changelog for v2.0.1

lib/bundle.js, test/techs/bemtree.test.js
=> Fixed bug with custom Vow for BEMTREE

package.json, techs/bem-xjst.js, techs/bemjson-to-html.js, test/techs/bemhtml/bemhtml--browser.test.js, test/techs/bemhtml/bemhtml--node.test.js, test/techs/bemhtml/bemhtml--ym.test.js, test/techs/bemhtml/bemhtml.test.js, test/techs/bemtree.test.js
=> Support ENB 1.x

lib/bundle.js
=> Fixed bug with provide to global scope

api.ru.md, techs/bemhtml.js, test/techs/bemhtml/bemhtml.test.js
=> Provide forceBaseTemplates option

techs/bemjson-to-html.js
Ref https://github.com/enb-bem/enb-bh/pull/126
=> Add render method to bemjsonToHtml tech

techs/bemjson-to-html.js
Add render method to bemjsonToHtml tech
Port of #121
=> Add render method

lib/assets/bundle.jst
SERP-49992 fixed
Port of https://github.com/enb/enb-bemxjst/commit/ca30a6c42684357b2bed4fdb15bece4893a21102
=> Support V8: there is no global there

package-lock.json, package.json, techs/bem-xjst.js
Instead of https://github.com/enb/enb-bemxjst/pull/280
cc @dustyo-O (sorry, I can’t push to your fork ;)
cc @tadatuta
=> Migrate to bem-xjst 8.8.4

techs/bem-xjst.js
=> Add possibility to disable sourcemaps
